### ISSUE TITLE
Error: 500 Internal Server Error on Hindsight

### ISSUE THREAD

**Issue by carlosmstraductor** [obsidianforensics/hindsight#43]
Dear sirs:
I would like to know what has happened when I tried to started Hinsight, since I followed all steps. It's my very first time using this programme.

Error: 500 Internal Server Error
Sorry, the requested URL 'http://localhost:8080/run' caused an error:

Internal Server Error
Exception:
AttributeError("'NoneType' object has no attribute 'selected_plugins'",)
Traceback:
Traceback (most recent call last):
File "site-packages\bottle.py", line 862, in _handle
File "site-packages\bottle.py", line 1732, in wrapper
File "hindsight_gui.py", line 130, in do_run
AttributeError: 'NoneType' object has no attribute 'selected_plugins'

Best regards from Spain
Carlos M.S.

**Comment by obsidianforensics** [comment]
Hi Carlos,

Can you provide a bit more information about how you are running it? What operating system are you using? Are you running the Python script, and if so, what version of Python? What were you doing when you encountered this error? Also, if you can attach or copy out the relevant portions of hindsight.log it might help debug this.

If you are on Windows and running the Python script, you might try the compiled exe; it might work better for you.

Thanks,
Ryan

**Comment by carlosmstraductor** [comment]
Dear Ryan,
My operating system is Windows 10 OS Version 1903
My version of Python is 3.8.2
I tried to use Hindsight on http://localhost:8080, but unsuccessfully.
I also selected all plugin selectors and my timezone is Zurich (+1/+2).

All the best,
Carlos M.S.

**Comment by obsidianforensics** [comment]
The latest release version of Hindsight only works on Python 2.7, so running it with Python 3.8 would explain those errors. The Python 3 version is in the works and will be out soon. In the meantime, I'd suggest using either Python 2.7 to run it, or using [hindsight_gui.exe](https://github.com/obsidianforensics/hindsight/releases/tag/v2.4.0), since you are on Windows.

**Comment by carlosmstraductor** [comment]
I tried again with Python 2,7, but here is the error, I'm very clumsy with this program since it's the very first time I use it.

Critical error while processing request: /run
Error:
UnicodeDecodeError('utf8', 'Traceback (most recent call last):\n  File "site-packages\\bottle.py", line 862, in _handle\n  File "site-packages\\bottle.py", line 1732, in wrapper\n  File "hindsight_gui.py", line 163, in do_run\n  File "pyhindsight\\analysis.py", line 438, in run\n  File "pyhindsight\\browsers\\chrome.py", line 1852, in process\n  File "pyhindsight\\browsers\\chrome.py", line 827, in get_extensions\nWindowsError: [Error 267] El nombre del directorio no es v\xe1lido: \'C:\\\\Users\\\\x\\\\AppData\\\\Local\\\\Google\\\\Chrome\\\\User Data\\\\ChromeDefaultData\\\\Extensions\\\\pbdpajcdgknpendpmecafmopknefafha/*.*\'\n', 434, 435, 'invalid continuation byte')
Traceback:
Traceback (most recent call last):
  File "site-packages\bottle.py", line 954, in wsgi
  File "site-packages\bottle.py", line 907, in _cast
  File "site-packages\bottle.py", line 842, in default_error_handler
  File "site-packages\bottle.py", line 3609, in template
  File "site-packages\bottle.py", line 3399, in render
  File "site-packages\bottle.py", line 3386, in execute
  File "<string>", line 26, in <module>
  File "site-packages\bottle.py", line 3337, in <lambda>
  File "site-packages\bottle.py", line 123, in touni
  File "encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 434: invalid continuation byte

All the best,
Carlos M.S.

**Comment by obsidianforensics** [comment]
I don't think you are doing anything wrong. It looks like Hindsight encountered some Unicode characters it couldn't handle. The new Python 3 version (coming out soon) should handle this better. In the meantime, if you need to process this Chrome installation (and Extensions aren't critical to your case), you can remove/rename the 'Extensions' directory in your input data and try running it again; hopefully it won't hit other errors.

**Comment by carlosmstraductor** [comment]
Hello again, I've got a new problem.
My main goal is actually recovering some links that disappeared from Chrome history on 11th March 2020 (March 11, 2020).

Here is the mistake:
Critical error while processing request: /run
Error:
UnicodeDecodeError('utf8', 'Traceback (most recent call last):\n  File "site-packages\\bottle.py", line 862, in _handle\n  File "site-packages\\bottle.py", line 1732, in wrapper\n  File "hindsight_gui.py", line 163, in do_run\n  File "pyhindsight\\analysis.py", line 438, in run\n  File "pyhindsight\\browsers\\chrome.py", line 1852, in process\n  File "pyhindsight\\browsers\\chrome.py", line 827, in get_extensions\nWindowsError: [Error 267] El nombre del directorio no es v\xe1lido: \'C:\\\\Users\\\\x\\\\AppData\\\\Local\\\\Google\\\\Chrome\\\\User Data\\\\ChromeDefaultData\\\\Extensions\\\\pbdpajcdgknpendpmecafmopknefafha/*.*\'\n', 434, 435, 'invalid continuation byte')
Traceback:
Traceback (most recent call last):
  File "site-packages\bottle.py", line 954, in wsgi
  File "site-packages\bottle.py", line 907, in _cast
  File "site-packages\bottle.py", line 842, in default_error_handler
  File "site-packages\bottle.py", line 3609, in template
  File "site-packages\bottle.py", line 3399, in render
  File "site-packages\bottle.py", line 3386, in execute
  File "<string>", line 26, in <module>
  File "site-packages\bottle.py", line 3337, in <lambda>
  File "site-packages\bottle.py", line 123, in touni
  File "encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 434: invalid continuation byte

Sorry for my insistence, I'm a little bit stubborn.

**Comment by obsidianforensics** [comment]
The error output looks the same as last time to me, am I missing something? If you are just interested in looking at History visits (which I think you are from your message), you can copy just the History file to it's own folder and run Hindsight against that folder. That should eliminate the error above, as it pertains to processing Extensions.
